# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

#### 2.Создать вектор размера 100, заполненный единицами

In [6]:
import numpy as np
Z = np.zeros(100)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [8]:
Z = np.ones(100)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#### 3.Создать вектор размера 100, заполненный числом 3

In [9]:
Z = np.full(100, 3)
print(Z)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Как получить документацию о функции numpy.add из командной строки?

In [11]:
python3 -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-11-e4a7e6a4f2e9>, line 1)

#### 5. Поменять 2 строки в матрице

#### 6. Создать вектор со значениями от 10 до 100

In [14]:
Z = np.arange(10,101,1)
print(Z)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


#### 7. Развернуть вектор (первый становится последним)

In [16]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [17]:
Z = np.arange(16).reshape(4,4)
print(Z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

#### 10. Создать 3x3 единичную матрицу

In [18]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Создать массив 3x3x3 со случайными значениями

In [19]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.40103236 0.68436826 0.85054269]
  [0.67379156 0.45388109 0.94536995]
  [0.76966495 0.11103132 0.99910801]]

 [[0.09484803 0.30879649 0.8877049 ]
  [0.65615086 0.75943354 0.62045598]
  [0.89350512 0.65654581 0.081655  ]]

 [[0.5953759  0.12772791 0.18361181]
  [0.25468453 0.97031843 0.19516481]
  [0.33124598 0.96825963 0.08512336]]]


#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [29]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Z)
print("Min: {0}, Max: {1}".format(Zmin, Zmax))

[[0.23087922 0.94993382 0.08782042 0.85731674 0.85494208 0.62604136
  0.26525664 0.41352879 0.3640332  0.7191866 ]
 [0.95305393 0.11492418 0.79928205 0.42992015 0.49828165 0.16928002
  0.6093407  0.87234264 0.40540724 0.7231115 ]
 [0.75663038 0.01813371 0.912588   0.11717864 0.60524126 0.19455212
  0.41615651 0.03367746 0.5578403  0.44210719]
 [0.27154343 0.4359504  0.02638085 0.61242308 0.74450113 0.64797095
  0.80490664 0.7309471  0.35841318 0.8433738 ]
 [0.31236851 0.17435531 0.94502056 0.1834488  0.00449805 0.82697101
  0.14179034 0.29094544 0.80083269 0.59072444]
 [0.14400755 0.66403041 0.20056605 0.60755414 0.81567461 0.42383646
  0.81904915 0.02047409 0.18636611 0.52813785]
 [0.88298382 0.27152744 0.18772856 0.143541   0.97108556 0.48323444
  0.34225891 0.85416132 0.15493845 0.92802874]
 [0.81105404 0.42837756 0.6030449  0.07441935 0.86878502 0.73752031
  0.00716604 0.24525394 0.97726888 0.92601358]
 [0.75746127 0.57187685 0.94368327 0.68671809 0.06153516 0.09948225
  0.71429403

#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [30]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4359256649567954


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [33]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [34]:
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [35]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [36]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Перемножить матрицы 5x3 и 3x2

In [37]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [60]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [59]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 24. Есть генератор, сделать с его помощью массив

In [58]:
def generate():
    for x in xrange(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

NameError: name 'xrange' is not defined

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [57]:
Z = np.linspace(0,1,12)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 26. Отсортировать вектор

In [56]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.09334004 0.18103028 0.23266557 0.26405164 0.30941829 0.3225936
 0.46278083 0.50293336 0.7865593  0.8877957 ]


#### 27. Проверить, одинаковы ли 2 numpy массива

In [55]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


#### 28. Сделать массив неизменяемым

In [54]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 29. Найти n наибольших значений в массиве

#### 30. Заменить максимальный элемент на ноль

In [53]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.53995766 0.27241896 0.37732711 0.13001643 0.1787289  0.
 0.10951898 0.13749442 0.76345726 0.18968589]


#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [52]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [51]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [50]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 34. Напечатать все значения в массиве

In [49]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((25,25))
print(Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [48]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

37


#### 36. Преобразовать массив из float в int

In [47]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [46]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. Случайно расположить p элементов в 2D массив

In [45]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)

#### 39. Отнять среднее из каждой строки в матрице

In [44]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.18867918 -0.13460574  0.29529052 -0.3908164  -0.2217786  -0.21334828
  -0.38558103  0.36239918  0.19553415  0.30422701]
 [-0.09104941  0.23944479  0.25036106  0.23785102 -0.565542   -0.46961523
  -0.36254447  0.04194421  0.38533854  0.3338115 ]
 [-0.07541337 -0.32150755  0.38325322  0.01096941  0.27416036  0.38834016
  -0.0327144  -0.33967202  0.08790498 -0.37532078]
 [-0.46559195  0.16779424  0.03686423 -0.48700322  0.39925631 -0.51313788
   0.26586274  0.43429643  0.44286498 -0.28120588]
 [-0.32711603  0.06066423  0.25474424 -0.16639426  0.22378589  0.2811321
  -0.22889037 -0.43016561  0.07786882  0.25437097]]


#### 40. Отсортировать матрицу по n-ому столбцу

In [42]:
Z = np.random.randint(0,10,(3,3))
n = 1  # Нумерация с нуля
print(Z)
print(Z[Z[:,n].argsort()])

[[8 6 4]
 [0 1 6]
 [5 2 6]]
[[0 1 6]
 [5 2 6]
 [8 6 4]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [41]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [40]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[5. 2. 6. 3. 2. 3. 3. 2. 2. 2.]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [39]:
w,h = 16,16
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [38]:
A = np.random.randint(0,10, (3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[62 66 45 42]
 [54 44 45 61]
 [41 62 57 57]]
